var APPLICATION_ID = 96465;
var AUTH_KEY = "zhxr4Xm88NBJvWT";
var AUTH_SECRET = "QMTwXjCHLmHDmLv";
var ACCOUNT_KEY = "SryGxD8QXQzbvy5aNpeu";
var CONFIG = { debug: {mode:1} };

QB.init(APPLICATION_ID, AUTH_KEY, AUTH_SECRET, ACCOUNT_KEY, CONFIG);